dist: trusty
sudo: required
language: cpp

compiler:
  - gcc
  - clang

env:
  matrix:
    - CONFIG=Release
	- CONFIG=Debug

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; export CXX="g++-4.9"; export CC="gcc-4.9"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; export CXX="clang++-3.6"; export CC="clang-3.6"; fi

before_script:
  - $CC --version
  - $CXX --version
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -Hsrc -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd build
  - make
  - ./YAIP++
